### PR TITLE
Write docs

### PR DESCRIPTION
**Pull request by jonodrew**
Once this is completed, users will be able to read how to download and run this software locally. They'll also be aware of all of the technical things I can think of.

### CODE REVIEW

**Comment by jonodrew** [comment]
@johnpeart can you `docker-compose up` this locally, and tell me if you can see the docs? Should be on `localhost:4000`

**Comment by johnpeart** [comment]
> @johnpeart can you `docker-compose up` this locally, and tell me if you can see the docs? Should be on `localhost:4000`

Yes I do! Cool that it runs both at once!

**Comment by johnpeart** [comment]
Just realised I didn't add a 404 page. Easy to fix, will commit directly to this branch (it won't affect what you've done).

**Comment by jonodrew** [comment]
@johnpeart can you please look over the documentation and tell me what you think? Also add the privacy and cookies stuff, if you like

**Comment by johnpeart** [comment]
Not entirely sure why, but on the Cookies page from :5001, the change we previously made seems to have disappeared!
This was mentioned in #103

**Comment by johnpeart** [comment]
Looks good. 

I've made a few changes – mostly just to make it a bit more assertive in places (as a bit of a software noob, I always find the more explicit the docs are and the plainer the English, the better!).

I've also moved the other docs across as discussed.

I've also added a 'Contributing' and 'Licences' page.

I assume you want to release this under the [Open Government Licence v3.0](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/)? That's what GOV.UK uses and it's what we've used on other stuff we produce.

We'll need to redirect "/cookies" and "/privacy" from Redis to Jekyll.
Is that just a case of changing the `.route("/cookies")` to `.route("http://docs.mentoring.service.civilservice.lgbt/cookies")`?

**Comment by jonodrew** [comment]
> Looks good.
> 
> I've made a few changes – mostly just to make it a bit more assertive in places (as a bit of a software noob, I always find the more explicit the docs are and the plainer the English, the better!).
> 
> I've also moved the other docs across as discussed.
> 
> I've also added a 'Contributing' and 'Licences' page.
> 
> I assume you want to release this under the [Open Government Licence v3.0](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/)? That's what GOV.UK uses and it's what we've used on other stuff we produce.

Yup, it's produced mostly on work time.

> We'll need to redirect "/cookies" and "/privacy" from Redis to Jekyll. Is that just a case of changing the `.route("/cookies")` to `.route("http://docs.mentoring.service.civilservice.lgbt/cookies")`?

Almost! We'll need to do a `redirect(<url>)`, and make sure we've got a clean way for the user to get back to where they were

Would you mind also then adding something to CHANGELOG.md, detailing the changes? Under a new heading, 2.6.0

**Comment by johnpeart** [comment]
The last commit (ff5c1fe) should (I hope!) fix the routing.

> [...] and make sure we've got a clean way for the user to get back to where they were

I suggest we handle this through links added to the header and footer. Can I suggest we create a separate branch for this, that encompasses fixing all the navigation?

**Comment by johnpeart** [comment]
Aside from the docs you need to add to, I think my work on this branch is done!
I will create a new branch to fix the navigation across the header, footer and breadcrumbs.

**Review by johnpeart — CHANGES_REQUESTED** [review]
There's one more doc to write up (aws.md) and there's a missing `https://` in the Notify doc. Aside form that, looks good to go!

**Review by johnpeart — APPROVED** [review]

**Pull request merged**
