### PR TITLE
Replace dialog with download page

### PR DESCRIPTION
**Pull request by johnpeart**
@jonodrew this is my attempt to get it all working without the dialog, per #55.

I've done a number of things to get the flow in place; not all of them work fully as I need your help. 

The main things I've done are:

- split the `base` template into two page styles: 1. with a header and 2. with a panel
- updated the other templates to account for this
- attempted to add the new routes – this will need checking closely!
- removed the JS for the dialog and put in placeholders that simply redirect the user to the next page in the process – this will also need checking closely

Grateful for your thoughts and ideas!

### CODE REVIEW

**Comment by jonodrew** [comment]
There's a lot going on here!
On the templating: I like your use of `extend`. Can you change the variable names to use snake_case? At the moment they're a little difficult to read. Additionally, where you've written in new blocks, please don't use placeholder text - it increases the risk that it sneaks onto the page if we forget to override it.

I see you've added a download page on the existing `download/<task_id>` route - I'm going to move that to its own `download` route. The route with the <task_id> is the one we use for deleting the data, so let's keep that separate.

I'll add some commits to this branch

**Comment by jonodrew** [comment]
Thinking about the user journey:
-> click `process` -> js polls backend, user waits for task to complete (some kind of spinner would be good here) -> js redirects to `/download`, somehow passes through task_id at the same time -> user clicks `Download` button, receives data -> data is deleted

**Comment by jonodrew** [comment]
Okay, I've tidied up the routes. I'm currently working on whether the javascript can call a route on Flask and still download to the client - only one way to find out I suppose!

**Comment by jonodrew** [comment]
Downloading via javascript [appears to be a bit tricky](https://stackoverflow.com/questions/32545632/how-can-i-download-a-file-using-window-fetch), and I'm not keen to add more javascript libraries when it's not a language I'm comfortable in.

Can we leave the 'finish' page out for the moment?

**Comment by johnpeart** [comment]
> Downloading via javascript [appears to be a bit tricky](https://stackoverflow.com/questions/32545632/how-can-i-download-a-file-using-window-fetch), and I'm not keen to add more javascript libraries when it's not a language I'm comfortable in.
>  
> Can we leave the 'finish' page out for the moment?

I think this might be overcomplicating it a bit?

If I've understood the backend code, and how you put it in the front end, you're just dumping a string into the URL and then the browser triggers a download.

If that's right, then you should be able to:

1. add a 'download' attribute to the `<a>` link
2. add a separate `onClick` attribute to trigger the redirect

I've pushed a change that I think works?

Only thing to check is that the deletion of the files works as you're expecting?

**Review by jonodrew — APPROVED** [review]

**Pull request merged**
