### PR TITLE
Add characteristics

### PR DESCRIPTION
**Pull request by jonodrew**
This is a huge change for what seemed like a small task. The aim is for mentees to be able to selet a characteristic against which they'd like to be matched, and for mentors to be able to select some number of characteristics that they have.

To do this I've subclassed the `Mentor`, `Mentee`, and `ParticipantFactory` classes from the matching library. Consequently I've had to rewrite a fairly significant chunk of this software. However, I think it's slightly better now, with more tests and a clearer separation of concerns.

### CODE REVIEW

**Comment by jonodrew** [comment]
@johnpeart - can you please look at the new mentors.csv and mentees.csv and confirm that the headings are correct? These are the expected inputs from here on in, so it's important they're right from the outset

**Comment by johnpeart** [comment]
I've added into both `mentees.csv` and `mentors.csv` two columns from the Google Sheet template: `mentor only` and `mentee only`.

In the Google Sheet, the `mentor only`, `mentee only` and `both mentor and mentee` columns are calculated by formula in the spreadsheets. All three are required for the outputs because the email templates use conditional tags for their content.

**Comment by johnpeart** [comment]
@jonodrew Aside from one minor edit, I think this all lines up.

I'm making the assumption that any column that is not required for the matching process is simply ignored and discarded.

**Comment by jonodrew** [comment]
It's good to know they're needed for the output. However, for the input, I think it's true to say that if a line is in the "mentees.csv" file *and* has a "no" in the "both mentor and mentee" column, then logically they are "mentee only" ?

**Comment by johnpeart** [comment]
> It's good to know they're needed for the output. However, for the input, I think it's true to say that if a line is in the "mentees.csv" file _and_ has a "no" in the "both mentor and mentee" column, then logically they are "mentee only" ?

Yes, that's right – so you could ignore it on the input and just generate it for the output.

**Comment by jonodrew** [comment]
Okay. In that case I'm going to revert your changes and just include that column in the output CSVs, which I'll get started on tomorrow.

**Pull request merged**
