### PR TITLE
Create class outputs

### PR DESCRIPTION
**Pull request by jonodrew**
### Changed

- The spreadsheet outputs have radically changed. This aligns with changes needed by the CSLGBTQ+ network for the next
  round of mentoring. In future releases, I'm going to try to generalise these changes so that other networks can
  use the system with greater ease. However, if you relied on the old spreadsheet, **DO NOT UPDATE TO THIS VERSION**.
  The new headings are:

| first name | last name | email address | number of matches | mentor only | mentee only | both mentor and mentee | match details |
|------------|-----------|---------------|-------------------|-------------|-------------|------------------------|---------------|

- the weightings have also changed:

| quality                    | old weighting | new weighting |
|----------------------------|---------------|---------------|
| exactly 2 grades different | 6             | 12            |
| exactly 1 grade different  | 3             | 9             |
| target profession          | 5             | 10            |
| characteristic match       | 4             | 6             |

### CODE REVIEW

**Comment by jonodrew** [comment]
@johnpeart could you pull this branch and check it runs okay, using the inputs in the app/static/data folder?

**Comment by johnpeart** [comment]
I'm getting an error when trying to run the app:

```
import matching.rules.rule as rl
mentor-match-app-1     | ModuleNotFoundError: No module named 'matching.rules'
```

**Comment by jonodrew** [comment]
I've done that now. Here's a table. I think it looks confusing at first glance but I hope it makes sense. There are four possible things we match on: exactly two grade difference, exactly one grade difference, profession, and characteristic. They're binary matches, which means there are 4<sup>2</sup> different combinations. You can discard the last four lines, because we can never have a match that has exactly two **and** exactly one grade difference. The scores are:

| quality | weighting |
|----|----|
| exactly 2 grades different | 6 |
| exactly 1 grade different  | 3 |
| target profession          | 5 |
| characteristic match       | 4 |

| exactly 2 grades different | exactly 1 grade different | target profession | characteristic match | score   |
| -------------------------- | ------------------------- | ----------------- | -------------------- | ------- |
| FALSE                      | FALSE                     | FALSE             | FALSE                | 0  |
| FALSE                      | FALSE                     | FALSE             | TRUE                 | 4  |
| FALSE                      | FALSE                     | TRUE              | FALSE                | 5  |
| FALSE                      | FALSE                     | TRUE              | TRUE                 | 9  |
| FALSE                      | TRUE                      | FALSE             | FALSE                | 3  |
| FALSE                      | TRUE                      | FALSE             | TRUE                 | 7  |
| FALSE                      | TRUE                      | TRUE              | FALSE                | 8  |
| FALSE                      | TRUE                      | TRUE              | TRUE                 | 12 |
| TRUE                       | FALSE                     | FALSE             | FALSE                | 6  |
| TRUE                       | FALSE                     | FALSE             | TRUE                 | 10 |
| TRUE                       | FALSE                     | TRUE              | FALSE                | 11 |
| TRUE                       | FALSE                     | TRUE              | TRUE                 | 15 |
| TRUE                       | TRUE                      | FALSE             | FALSE                | 9  |
| TRUE                       | TRUE                      | FALSE             | TRUE                 | 13 |
| TRUE                       | TRUE                      | TRUE              | FALSE                | 14 |
| TRUE                       | TRUE                      | TRUE              | TRUE                 | 18 |

As you can see, the scores don't uniformly improve. The highest score is, as you'd expect, a 2-grade difference with the right profession and a characteristic match. 

The next highest is the same, except a 1-grade difference. Is that right? I'm not sure.

Essentially I'm afraid what I need from you (or a subordinate!) is a ranking of the 12 possible combinations, so that I can work out the optimal weightings to create that ranking.

**Comment by johnpeart** [comment]
OK, so if I've understood the ranking properly:

- the best outcome is 2 grade gap *and* profession match *and* characteristics match – which is objectively correct
- the next best outcome is a 1 grade gap *and* a profession match *and* a characteristic match – which I think is also objectively right 
- the worst outcome is no match on any basis – which, again, is objectively true

In between those are value judgments.

I think that

- the grade gap match is ~more~ important than the profession *or* characteristic match
- the profession match is ~more~ important than the characteristic match
- a match on grade gap *and* profession is ~more~ important than only one of those matching *and* a characteristic match

I think that translates into the table as follows...

| exactly 2 grades different | exactly 1 grade different | target profession | characteristic match | score | rank |
| -------------------------- | ------------------------- | ----------------- | -------------------- | ----- | ---- |
| TRUE                       | FALSE                     | TRUE              | TRUE                 | 15    | 1    |
| FALSE                      | TRUE                      | TRUE              | TRUE                 | 12    | 2    |
| TRUE                       | FALSE                     | TRUE              | FALSE                | 11    | 3    |
| TRUE                       | FALSE                     | FALSE             | TRUE                 | 10    | 5     |
| FALSE 🚨                   | FALSE 🚨                  | TRUE              | TRUE                 | 9     | ?    |
| FALSE                      | TRUE                      | TRUE              | FALSE                | 8     | 4    |
| FALSE                      | TRUE                      | FALSE             | TRUE                 | 7     | 6    |
| TRUE                       | FALSE                     | FALSE             | FALSE                | 6     | 7    |
| FALSE 🚨                   | FALSE 🚨                  | TRUE              | FALSE                | 5     | ?    |
| FALSE 🚨                   | FALSE 🚨                  | FALSE             | TRUE                 | 4     | ?    |
| FALSE                      | TRUE                      | FALSE             | FALSE                | 3     | 8    |
| FALSE 🚨                   | FALSE 🚨                  | FALSE             | FALSE                | 0     | 9    |

You'll see I've stuck some alarm emojis in that list: I don't think these outcomes should be possible – it is a pre-requisite that a mentor must be at least one and ideally 2 grades more senior than their mentee. A match with someone that is neither exactly 2 or exactly 1 grade higher shouldn't, on that basis, be possible in this ranking and should score 0?

I've not amended the 'score' column about – just put in the rank order I think it should be.

What do you think?

**Comment by jonodrew** [comment]
Yes, very well spotted! I had forgotten for a moment that if there's no grade match at all the match should be disqualified. With that ranking, I can put in the numbers to get to where we need to be. Thanks John!

**Comment by johnpeart** [comment]
Great. I'll re-run the sample data and look to review the outputs this week as a final check.

**Pull request closed without merging**
