### PR TITLE
Use route to ensure deletion

### PR DESCRIPTION
**Pull request by jonodrew**
I've altered the button so that it uses the route, rather than downloading it. This is because the route itself has a post-request function that deletes the file once it's been downloaded. This prevents sensitive data hanging around on the server any longer than we need it.

### CODE REVIEW

**Review by johnpeart — APPROVED** [review]
I don't entirely follow what the changes are here – I assume the `routes.py` change is the significant one – but I've tested it and it seems to work!

**Comment by jonodrew** [comment]
Ah yes, it looks like a lot of whitespace has been added. The key change is actually to `main.js`- I've accessed the `downloadButton` directly from its `id` and set it to use the route, rather than downloading it. The effect is the same, but this change means that the request actually hits the server, and triggers the auto-delete.

Thanks for approving - I'll merge now

**Comment by johnpeart** [comment]
Having looked at the `routes.py` file a bit closer, I assume it's this bit that needs to be re-examined to delete the ZIP file?

```python
@main_bp.route("/download/<task_id>", methods=["GET"])
def download(task_id):
    data_path = pathlib.Path(current_app.config["UPLOAD_FOLDER"], task_id)
    current_app.logger.debug(data_path)
    if request.method == "GET":

        @after_this_request
        def remove_file(response):
            try:
                shutil.rmtree(data_path)
            except Exception as error:
                current_app.logger.error(
                    "Error removing or closing downloaded file handle", error
                )
            return response

        shutil.make_archive(
            base_name=f"{pathlib.Path(current_app.config['UPLOAD_FOLDER']).__str__()}/matches",
            format="zip",
            root_dir=data_path,
        )
        return send_from_directory(
            directory=pathlib.Path(current_app.config["UPLOAD_FOLDER"]),
            path="matches.zip",
        )
```

The `remove_file` def doesn't appear to be called to remove the `matches.zip` folder (but my python is not as good as it should be so I may be wrong!)

**Comment by jonodrew** [comment]
Ah very good spot! Let me write a test and then we can fix this up.

**Pull request merged**
